# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
   imageName: 'pipelines-javascript-docker'

  # Agent VM image name
pool:
  vmImageName: 'ubuntu-latest'

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '2.14.1'
    installKubectl: true

