# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
   imageName: 'pipelines-javascript-docker'

  # Agent VM image name
pool:
  vmImageName: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: 'app/Dockerfile'
    repository: $(imageName)

