trigger:
- master

variables:
   imageName: 'pipelines-javascript-docker'

  # Agent VM image name
pool:
  vmImageName: 'ubuntu-latest'

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.9.4'
    installKubectl: true

